### ISSUE TITLE
Ramp up/down of turning code to prevent motor burn out

### ISSUE THREAD

**Issue by admalledd** [team2517/2014FRC#11]
if we suddenly rotate in one direction then another in the opposite direction the motor is put under undue strain. make sure to not change direction too fast.

**Comment by gint271** [comment]
Need to test both ways of spark control with added mass and resistance of a wheel in contact with the ground.

**Comment by gint271** [comment]
Current method of setting motors to 0 before reversing direction works.  No need for further testing.
