### ISSUE TITLE
Ball Shooter

### ISSUE THREAD

**Issue by gint271** [team2517/2014FRC#4]
Code the pneumatics and motors for either catapult or kicker.

**Comment by gint271** [comment]
Also, we may need to slow the drive while we fire to avoid tripping a breaker.  This could be done with a simple multiplier being applied to the magnitudes when we fire.

**Comment by admalledd** [comment]
Before we go that far I think it might be a good idea to take a ammeter to the robot first (or a equivlent test bed) running motors at full speed (eg `motor.set(1.0)`) != using the full amperage. See [here](http://files.andymark.com/CIM-motor-curve.pdf) on the bottom left is a small chart with torque numbers and the current therefore. "Expected maximum" along the CIM motors curve is something along the lines of 20~ amps max. Of course it can peak higher - eg when pushing another robot - but that is not the norm. Hence we would want to check with electrical about doing a simulated load test (simulate all "commonly active" motors stressed at 75%, and then another test stressing all "unlikely active" motors as well to 90% (don't go higher, might burn up some motors!).)

**Comment by tylerscheuble** [comment]
Fixed in commit https://github.com/team2517/2014FRC/commit/7670424794d40bc640b31ef6bea68613ee0db117#diff-ffad92ae8e6749b385235bc7acc3faca. Closed.

**Comment by tylerscheuble** [comment]
Not tested or proven to work. Reopening.

**Comment by tylerscheuble** [comment]
Done. Closing.
