### ISSUE TITLE
Over-the-Bumper Pickup Motors

### ISSUE THREAD

**Issue by gint271** [team2517/2014FRC#5]
Code the motors for the Over-the-Bumper pickup.

**Comment by gint271** [comment]
Pickup consists of two window motors running off of jaguars.  They need to move down in sync and then up in sync.

**Comment by gint271** [comment]
Code currently has one button move down, and another button to move them back up.
Added in commit:
4a79d4ae92fb2227aa946220413626fc42c12463

**Comment by tylerscheuble** [comment]
Completed. Closing.
