### ISSUE TITLE
Shut down swerve module on demand to prevent further damage

### ISSUE THREAD

**Issue by admalledd** [team2517/2014FRC#8]
in case of failure on field be able to shut down a specific individual module to prevent further damage.

**Comment by tylerscheuble** [comment]
For doing this, we have 2 options.

1: Have a second joystick with the buttons programmed to shut off specific modules. 

2: We figure out how to use digital buttons in the driver station software.

**Comment by admalledd** [comment]
I prefer the second joystick due to how hard it might be to use the touchpad in the heat of the moment at competition.

Nothing against using the dashboard LED output stuffs to show which one is on/off though.
